# Generated by Django 2.2 on 2022-11-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=50)),
                ('kegiatan', models.TextField()),
            ],
        ),
    ]
